rank=5 L00: Traceback (most recent call last):
rank=5 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=5 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=5 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=5 L04:     pkg_name=pkg_name, script_name=fname)
rank=5 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=5 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=5 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=5 L08:     exec(code, run_globals)
rank=5 L09:   File "task7.py", line 163, in <module>
rank=5 L10:     ph.read(acoustic=True)
rank=5 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=5 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=5 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 5): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=6 L00: Traceback (most recent call last):
rank=6 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=6 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=6 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=6 L04:     pkg_name=pkg_name, script_name=fname)
rank=6 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=6 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=6 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=6 L08:     exec(code, run_globals)
rank=6 L09:   File "task7.py", line 163, in <module>
rank=6 L10:     ph.read(acoustic=True)
rank=6 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=6 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=6 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 6): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=1 L00: Traceback (most recent call last):
rank=1 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=1 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=1 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=1 L04:     pkg_name=pkg_name, script_name=fname)
rank=1 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=1 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=1 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=1 L08:     exec(code, run_globals)
rank=1 L09:   File "task7.py", line 163, in <module>
rank=1 L10:     ph.read(acoustic=True)
rank=1 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=1 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=1 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 1): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=2 L00: Traceback (most recent call last):
rank=2 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=2 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=2 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=2 L04:     pkg_name=pkg_name, script_name=fname)
rank=2 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=2 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=2 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=2 L08:     exec(code, run_globals)
rank=2 L09:   File "task7.py", line 163, in <module>
rank=2 L10:     ph.read(acoustic=True)
rank=2 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=2 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=2 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 2): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=3 L00: Traceback (most recent call last):
rank=3 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=3 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=3 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=3 L04:     pkg_name=pkg_name, script_name=fname)
rank=3 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=3 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=3 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=3 L08:     exec(code, run_globals)
rank=3 L09:   File "task7.py", line 163, in <module>
rank=3 L10:     ph.read(acoustic=True)
rank=3 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=3 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=3 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 3): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=4 L00: Traceback (most recent call last):
rank=4 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=4 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=4 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=4 L04:     pkg_name=pkg_name, script_name=fname)
rank=4 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=4 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=4 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=4 L08:     exec(code, run_globals)
rank=4 L09:   File "task7.py", line 163, in <module>
rank=4 L10:     ph.read(acoustic=True)
rank=4 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=4 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=4 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 4): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=7 L00: Traceback (most recent call last):
rank=7 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=7 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=7 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=7 L04:     pkg_name=pkg_name, script_name=fname)
rank=7 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=7 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=7 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=7 L08:     exec(code, run_globals)
rank=7 L09:   File "task7.py", line 163, in <module>
rank=7 L10:     ph.read(acoustic=True)
rank=7 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=7 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=7 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 7): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=8 L00: Traceback (most recent call last):
rank=8 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=8 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=8 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=8 L04:     pkg_name=pkg_name, script_name=fname)
rank=8 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=8 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=8 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=8 L08:     exec(code, run_globals)
rank=8 L09:   File "task7.py", line 163, in <module>
rank=8 L10:     ph.read(acoustic=True)
rank=8 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=8 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=8 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 8): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=9 L00: Traceback (most recent call last):
rank=9 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=9 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=9 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=9 L04:     pkg_name=pkg_name, script_name=fname)
rank=9 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=9 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=9 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=9 L08:     exec(code, run_globals)
rank=9 L09:   File "task7.py", line 163, in <module>
rank=9 L10:     ph.read(acoustic=True)
rank=9 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=9 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=9 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 9): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=0 L00: Traceback (most recent call last):
rank=0 L01:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/GPAW/19.8.1-Python-3.7.2/lib/python3.7/site-packages/gpaw/__init__.py", line 209, in main
rank=0 L02:     runpy.run_path(gpaw_args.script, run_name='__main__')
rank=0 L03:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 263, in run_path
rank=0 L04:     pkg_name=pkg_name, script_name=fname)
rank=0 L05:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 96, in _run_module_code
rank=0 L06:     mod_name, mod_spec, pkg_name, script_name)
rank=0 L07:   File "/apps/Hebbe7/software/Compiler/GCCcore/8.2.0/Python/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
rank=0 L08:     exec(code, run_globals)
rank=0 L09:   File "task7.py", line 163, in <module>
rank=0 L10:     ph.read(acoustic=True)
rank=0 L11:   File "/apps/Hebbe7/software/MPI/intel/2019.1.144-GCC-8.2.0-2.31.1/impi/2018.4.274/ASE/3.18.0-Python-3.7.2/lib/python3.7/site-packages/ase/phonons.py", line 407, in read
rank=0 L12:     C_Nav = C_av.reshape((N, len(self.atoms), 3))[:, self.indices]
rank=0 L13: ValueError: cannot reshape array of size 48 into shape (64,2,3)
GPAW CLEANUP (node 0): <class 'ValueError'> occurred.  Calling MPI_Abort!
